#!/bin/sh

DEFAULT_MYSQL_USER="exporter"
DEFAULT_MYSQL_PASSWORD="exporterpasswd"
DEFAULT_MYSQL_PORT="3306"
DEFAULT_MYSQL_HOST="localhost"


# mysql.port
mysql_port()
{
    port="$(snapctl get mysql.port)"
    if [ -z "$port"]; then
        port="$DEFAULT_MYSQL_PORT"
        set_mysql_port $port
    fi
    echo "$port"
}

set_mysql_port()
{
    snapctl set mysql.port="$1"
}

# mysql.host
mysql_host()
{
    host="$(snapctl get mysql.host)"
    if [ -z "$host"]; then
        host="$DEFAULT_MYSQL_HOST"
        set_mysql_host $host
    fi
    echo "$host"
}

set_mysql_host()
{
    snapctl set mysql.host="$1"
}

# mysql.user
mysql_user()
{
    user="$(snapctl get mysql.user)"
    if [ -z "$user"]; then
        user="$DEFAULT_MYSQL_USER"
        set_mysql_user $user
    fi
    echo "$user"
}

set_mysql_user()
{
    snapctl set mysql.user="$1"
}


# mysql.password
mysql_password()
{
    new_password="$(snapctl get mysql.password)"
    if [ -z "$new_password"]; then
        new_password="$DEFAULT_MYSQL_PASSWORD"
        set_mysql_passwordd $new_password
    fi
    echo "$new_password"
}

set_mysql_password()
{
    snapctl set mysql.password="$1"
}


# common
restart()
{
    snapctl restart mysqld-exporter.mysqld-exporter
}

generate_mycnf()
{
    cp -p $SNAP/etc/prometheus/my.cnf $SNAP_DATA/my.cnf

    PROM_MYSQL_EXPORTER_MYSQL_USER="$(mysql_user)"
    PROM_MYSQL_EXPORTER_MYSQL_PASSWORD="$(mysql_password)"
    PROM_MYSQL_EXPORTER_MYSQL_HOST="$(mysql_host)"
    PROM_MYSQL_EXPORTER_MYSQL_PORT="$(mysql_port)"

    sed -i "s/MYSQL_USER/${PROM_MYSQL_EXPORTER_MYSQL_USER}/" $SNAP_DATA/my.cnf
    sed -i "s/MYSQL_PASSWORD/${PROM_MYSQL_EXPORTER_MYSQL_PASSWORD}/" $SNAP_DATA/my.cnf
    sed -i "s/MYSQL_HOST/${PROM_MYSQL_EXPORTER_MYSQL_HOST}/" $SNAP_DATA/my.cnf
    sed -i "s/MYSQL_PORT/${PROM_MYSQL_EXPORTER_MYSQL_PORT}/" $SNAP_DATA/my.cnf
}
