name: mysqld-exporter
base: core22
adopt-info: mysqld-exporter
summary: The mysqld prometheus exporter from the Prometheus community
description: |
  Provides the mysqld prometheus exporter from the Prometheus community as
  a snap for collecting metrics from a mysql server instance.

grade: devel
confinement: strict

apps:
  mysqld-exporter:
    command: 'bin/mysqld-exporter.wrapper'
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  mysqld-exporter:
    plugin: go
    build-snaps:
      - go
    source-type: git
    source: https://github.com/prometheus/mysqld_exporter.git
    source-tag: "v0.14.0"
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"

  mycnf:
    source: .
    plugin: dump
    organize:
      my.cnf: etc/prometheus/my.cnf
    prime:
      - etc/prometheus/my.cnf

  wrappers:
    source: .
    plugin: dump
    organize:
      wrappers/: bin/

  scripts:
    source: .
    plugin: dump
    organize:
      scripts/: bin/
