name: mysqld-exporter
base: core22
adopt-info: mysqld-exporter
summary: The mysqld prometheus exporter from the Prometheus community
description: |
  Provides the mysqld prometheus exporter from the Prometheus community as
  a snap for collecting metrics from a mysql server instance.

grade: devel
confinement: strict

apps:
  mysqld-exporter:
    command: 'bin/mysqld-exporter-service'
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  mysqld-exporter:
    plugin: go
    build-snaps:
      - go
    source-type: git
    source: https://github.com/prometheus/mysqld_exporter.git
    source-tag: "v0.14.0"
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe)"

  snap-hooks:
    source: .
    plugin: python
    build-packages:
      - git
    python-requirements:
      - requirements.txt
    override-build: |
      craftctl default
      snap-helpers write-hooks

  templates:
    source: templates/
    plugin: dump
    organize:
      '*': templates/
