#!/bin/sh

# NOTE(wolsen) Normally these would be written out by the
# snap-helpers write-hooks command, but it writes out a
# command-chain snapcraft-runner directive which is not
# recognized in core22. Need to determine if this is a bug
# or not in the snap-helpers. In the meantime, we'll just
# write the file directly.
exec "${SNAP}/bin/snap-helpers-hook" "install"
